export interface Province {
  code: string;
  name: string;
}

export const provinces: Province[] = [
  { code: "01", name: "Sở GD&ĐT Hà Nội" },
  { code: "02", name: "Sở GD&ĐT TP. Hồ Chí Minh" },
  { code: "03", name: "Sở GD&ĐT Hải Phòng" },
  { code: "04", name: "Sở GD&ĐT Đà Nẵng" },
  { code: "05", name: "Sở GD&ĐT Hà Giang" },
  { code: "06", name: "Sở GD&ĐT Cao Bằng" },
  { code: "07", name: "Sở GD&ĐT Lai Châu" },
  { code: "08", name: "Sở GD&ĐT Lào Cai" },
  { code: "09", name: "Sở GD&ĐT Tuyên Quang" },
  { code: "10", name: "Sở GD&ĐT Lạng Sơn" },
  { code: "11", name: "Sở GD&ĐT Bắc Kạn" },
  { code: "12", name: "Sở GD&ĐT Thái Nguyên" },
  { code: "13", name: "Sở GD&ĐT Yên Bái" },
  { code: "14", name: "Sở GD&ĐT Sơn La" },
  { code: "15", name: "Sở GD&ĐT Phú Thọ" },
  { code: "16", name: "Sở GD&ĐT Vĩnh Phúc" },
  { code: "17", name: "Sở GD&ĐT Quảng Ninh" },
  { code: "18", name: "Sở GD&ĐT Bắc Giang" },
  { code: "19", name: "Sở GD&ĐT Bắc Ninh" },
  { code: "21", name: "Sở GD&ĐT Hải Dương" },
  { code: "22", name: "Sở GD&ĐT Hưng Yên" },
  { code: "23", name: "Sở GD&ĐT Hòa Bình" },
  { code: "24", name: "Sở GD&ĐT Hà Nam" },
  { code: "25", name: "Sở GD&ĐT Nam Định" },
  { code: "26", name: "Sở GD&ĐT Thái Bình" },
  { code: "27", name: "Sở GD&ĐT Ninh Bình" },
  { code: "28", name: "Sở GD&ĐT Thanh Hóa" },
  { code: "29", name: "Sở GD&ĐT Nghệ An" },
  { code: "30", name: "Sở GD&ĐT Hà Tĩnh" },
  { code: "31", name: "Sở GD&ĐT Quảng Bình" },
  { code: "32", name: "Sở GD&ĐT Quảng Trị" },
  { code: "33", name: "Sở GD&ĐT Thừa Thiên Huế" },
  { code: "34", name: "Sở GD&ĐT Quảng Nam" },
  { code: "35", name: "Sở GD&ĐT Quảng Ngãi" },
  { code: "36", name: "Sở GD&ĐT Kon Tum" },
  { code: "37", name: "Sở GD&ĐT Bình Định" },
  { code: "38", name: "Sở GD&ĐT Gia Lai" },
  { code: "39", name: "Sở GD&ĐT Phú Yên" },
  { code: "40", name: "Sở GD&ĐT Đắk Lắk" },
  { code: "41", name: "Sở GD&ĐT Khánh Hòa" },
  { code: "42", name: "Sở GD&ĐT Lâm Đồng" },
  { code: "43", name: "Sở GD&ĐT Bình Phước" },
  { code: "44", name: "Sở GD&ĐT Bình Dương" },
  { code: "45", name: "Sở GD&ĐT Ninh Thuận" },
  { code: "46", name: "Sở GD&ĐT Tây Ninh" },
  { code: "47", name: "Sở GD&ĐT Đồng Nai" },
  { code: "48", name: "Sở GD&ĐT Bà Rịa - Vũng Tàu" },
  { code: "49", name: "Sở GD&ĐT Long An" },
  { code: "50", name: "Sở GD&ĐT Đồng Tháp" },
  { code: "51", name: "Sở GD&ĐT An Giang" },
  { code: "52", name: "Sở GD&ĐT Tiền Giang" },
  { code: "53", name: "Sở GD&ĐT Vĩnh Long" },
  { code: "54", name: "Sở GD&ĐT Bến Tre" },
  { code: "55", name: "Sở GD&ĐT Kiên Giang" },
  { code: "56", name: "Sở GD&ĐT Cần Thơ" },
  { code: "57", name: "Sở GD&ĐT Hậu Giang" },
  { code: "58", name: "Sở GD&ĐT Sóc Trăng" },
  { code: "59", name: "Sở GD&ĐT Bạc Liêu" },
  { code: "60", name: "Sở GD&ĐT Cà Mau" },
  { code: "61", name: "Sở GD&ĐT Điện Biên" },
  { code: "62", name: "Sở GD&ĐT Đắk Nông" },
  { code: "63", name: "Sở GD&ĐT Trà Vinh" },
  { code: "64", name: "Sở GD&ĐT Vĩnh Phúc" } // standard list mapped
];

export function getProvinceName(code: string): string {
  const prov = provinces.find(p => p.code === code);
  return prov ? prov.name : "Sở GD&ĐT Việt Nam";
}
